apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configuration-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/hyplex-services/overlays/configuration-service
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: hyplex-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
