apiVersion: v1
kind: ConfigMap
metadata:
  name: hyplex-services-config
  namespace: hyplex-world
data:
  REDIS_ADDR: "hyplex-redis.hyplex-redis.svc.cluster.local:6379"
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"
  # R2 Storage configuration
  R2_ENDPOINT_URL: "https://worlds.production.hyplex.gg"
  R2_BUCKET_NAME: "worlds"
