apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#resources:
#  - ../../base
helmCharts:
  - name: traefik
    version: "38.0.2"
    repo: https://helm.traefik.io/traefik
    releaseName: traefik-internal
    valuesFile: values.yaml
    namespace: traefik
