apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: nats
    version: "2.12.3"
    repo: https://nats-io.github.io/k8s/helm/charts/
    releaseName: nats
    namespace: nats
    valuesFile: values.yaml
