apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linear-notifier
  namespace: linear-notifier
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`linear-notifier.vngenterprise.com`)
      kind: Rule
      services:
        - name: linear-notifier
          port: 3000
  tls:
    certResolver: letsencrypt
