apiVersion: v1
kind: ConfigMap
metadata:
  name: hyplex-services-config
  namespace: hyplex-matchmaking
data:
  REDIS_ADDR: "hyplex-redis-master.hyplex-redis.svc.cluster.local:6379"
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  GSM_URL: "http://game-server-manager.hyplex-gsm.svc.cluster.local:8080"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"
