apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secret.yaml
  - ingress-api.yaml
  - ingress-console.yaml
helmCharts:
  - name: rustfs
    version: "0.0.80"
    repo: https://charts.rustfs.com
    releaseName: rustfs
    namespace: rustfs
    valuesFile: values.yaml
