apiVersion: v1
kind: ConfigMap
metadata:
  name: hyplex-services-config
  namespace: hyplex-player-profile
data:
  DB_HOST: "hyplex-pooler-rw.hyplex-pg.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "hyplex"
  DB_USER: "postgres"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"
