defaultBackupStore:
  backupTarget: s3://longhorn-backups@auto/
  backupTargetCredentialSecret: longhorn-backup-r2
  pollInterval: 300
defaultSettings:
  storageOverProvisioningPercentage: "300"
  replicaAutoBalance: best-effort
persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  disableRevisionCounter: "true"
#  backupTargetName: wasabi
#  recurringJobSelector:
#    enable: true
#    jobList:
#      - '[{"name":"wasabi-policy","isGroup":true}]'