longhornManager:
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
longhornDriver:
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
defaultBackupStore:
  backupTarget: s3://longhorn-backups@auto/
  backupTargetCredentialSecret: longhorn-backup-r2
  pollInterval: 300
defaultSettings:
  storageOverProvisioningPercentage: "300"
  replicaAutoBalance: best-effort
persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  disableRevisionCounter: "true"
  recurringJobSelector:
    enable: true
    jobList:
      - '{"name":"default","isGroup":true}'