persistence:
  defaultClass: false

defaultSettings:
  createDefaultStorageClass: false
  defaultLonghornStaticStorageClass: ""

defaultBackupStore:
  backupTarget: s3://vanguard-longhorn@us-east-1/
  backupTargetCredentialSecret: longhorn-backup-wasabi
  pollInterval: 300