apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-config
  namespace: pelican
data:
  APP_NAME: "Hyplex - Gdev"
  APP_URL: "https://gdev.vngenterprise.com"
  APP_DEBUG: "false"
  APP_ENV: "production"
  LE_EMAIL: "infra@vngenterprise.com"
  CACHE_STORE: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  REDIS_HOST: "cache.pelican.svc.cluster.local"
  DB_CONNECTION: "mariadb"
  DB_HOST: "database.pelican.svc.cluster.local"
  DB_PORT: "3306"
  XDG_DATA_HOME: "/pelican-data"
  MAIL_DRIVER: "log"
  BEHIND_PROXY: "true"
  SKIP_CADDY: "false"
  SUPERVISORD_CADDY: "true"
  APP_INSTALLED: "true"
