apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pelican
  namespace: pelican
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gdev.vngenterprise.com`)
      kind: Rule
      services:
        - name: panel
          port: 443
          scheme: https
  tls:
    store:
      name: default
      namespace: traefik
