apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - external-secret.yaml
  - pvc.yaml
  #- certificate.yaml
  - database.yaml
  - cache.yaml
  - panel.yaml
  - ingress.yaml
  - service.yaml