apiVersion: v1
kind: Service
metadata:
  name: hyplex-proxy
  namespace: hyplex-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.50.190
  ports:
    - name: quic
      port: 25565
      targetPort: 25565
      protocol: UDP
    - name: messaging
      port: 25570
      targetPort: 25570
      protocol: UDP
  selector:
    app: hyplex-proxy
