apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-6.yaml
  - backup-daily.yaml
  - backup-weekly.yaml
  - backup-monthly.yaml
  - snapshot-30.yaml
  - system-backup-24.yaml