datasources:
  datasources.yaml:
    datasources:
      - name: Mimir-Pods-Tenant
        type: prometheus
        access: proxy
        orgId: 1
        url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
        isDefault: true
        version: 1
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          alertmanagerUid: "alertmanager"
        secureJsonData:
          httpHeaderValue1: "pods"
persistence:
  storageClassName: longhorn
  enabled: true
  size: 1Gi
grafana.ini:
  grafana_net:
    url: https://grafana.vngenterprise.com
  server:
    root_url: https://grafana.vngenterprise.com
  auth.generic_oauth:
    enabled: true
    name: "VANGUARD SSO"
    allow_sign_up: true
    client_id: "327050265184241030"
    auth_url: https://accounts.vngenterprise.com/oauth/v2/authorize
    token_url: https://accounts.vngenterprise.com/oauth/v2/token
    api_url: https://accounts.vngenterprise.com/oidc/v1/userinfo
    role_attribute_path: "contains(groups[*], 'monitoring_admin') && 'GrafanaAdmin' || contains(groups[*], 'monitoring_editor') && 'Editor' || 'Viewer'"
    allow_assign_grafana_admin: true
    role_attribute_strict: true
    email_attribute_name: "email:primary"
    email_attribute_path: "email"
    scopes: "openid email profile offline_access roles"
    auto_login: true
    use_pkce: true
    use_refresh_token: true
deploymentStrategy:
  type: Recreate