apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: rustlens
spec:
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: github-pull-secret
      containers:
        - name: worker
          image: ghcr.io/vanguard-enterprise/rustlens-agent-worker:b03eebbfa53701489f722dbf31002beba5bc9e2c
          envFrom:
            - secretRef:
                name: rustlens-secrets
