apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: rustlens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: github-pull-secret
      containers:
        - name: worker
          image: ghcr.io/vanguard-enterprise/rustlens-agent-worker:c0c3cb635f61fe2a5674ff5c75edc4e880e27329
          envFrom:
            - secretRef:
                name: rustlens-secrets
          volumeMounts:
            - name: worker-config
              mountPath: /app/worker-config
              readOnly: true
          command:
            - /bin/sh
            - -c
            - cp /app/worker-config/config.json /app/config.json && cp /app/worker-config/identity.json /app/identity.json && npm start
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: worker-config
          persistentVolumeClaim:
            claimName: worker-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-config-pvc
  namespace: rustlens
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
