apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - prometheusrule.yaml
helmCharts:
  - name: alloy
    version: 1.4.0
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy-metrics
    namespace: alloy-metrics
    valuesFile: values.yaml