apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: cloudnative-pg
    version: "0.26.1"
    repo: https://cloudnative-pg.io/charts/
    releaseName: cloudnative-pg
    namespace: cnpg-operator
    #valuesFile: values.yaml