apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-postgres
  namespace: temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-postgres
  template:
    metadata:
      labels:
        app: temp-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: temp-postgres-password
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: LANG
              value: en_US.utf8
            - name: POSTGRES_INITDB_ARGS
              value: "--locale=en_US.utf8 --encoding=UTF8 --text-search-config=english"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: temp-postgres-data
