apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mimir.vngenterprise.com.yaml
  - external-secret.yaml
helmCharts:
  - name: mimir
    version: "6.0.3"
    repo: https://grafana.github.io/helm-charts
    releaseName: mimir-distributed
    namespace: mimir
    valuesFile: values.yaml
