minio:
  enabled: false
vaultAgent:
  enabled: false
alertmanager:
  enabled: false
gateway:
  enabled: true
store_gateway:
  zoneAwareReplication:
    enabled: false
kafka:
  enabled: false
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          bucket_name: "${RULER_BUCKET_NAME}"
          endpoint: "${BUCKET_ENDPOINT}"
          insecure: false
          access_key_id: "${AWS_ACCESS_KEY_ID}"
          secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    tenant_federation:
      enabled: true
    blocks_storage:
      s3:
        bucket_name: "${TSDB_BUCKET_NAME}"
    alertmanager_storage:
      s3:
        bucket_name: "${RULER_BUCKET_NAME}"
    ruler_storage:
      s3:
        bucket_name: "${RULER_BUCKET_NAME}"
    ingest_storage:
      enabled: false
    ingester:
      push_grpc_method_enabled: true
ingester:
  replicas: 1
  statefulSet:
    enabled: true
  persistentVolume:
    size: 2Gi
    storageClass: "longhorn"
  zoneAwareReplication:
    enabled: false
global:
  extraEnvFrom:
    - secretRef:
        name: mimir-global-env