apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - game-namespace.yaml
helmCharts:
  - name: agones
    version: 1.45.0
    repo: https://agones.dev/chart/stable
    releaseName: agones
    namespace: agones-system
    valuesFile: values.yaml
