apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secrets.yaml
  - redis-replication.yaml
  - redis-sentinel.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
