apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: worlds-frontend
  namespace: worlds-frontend
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`worlds.vngenterprise.com`)
      kind: Rule
      services:
        - name: worlds-frontend
          port: 3000
  tls:
    store:
      name: default
      namespace: traefik-internal
