apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-external
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-internal
spec:
  controller: traefik.io/ingress-controller