apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-oauth2-proxy
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: client-id
      remoteRef:
        key: monitoring/mimir
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: monitoring/mimir
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: monitoring/mimir
        property: cookie-secret