apiVersion: v1
kind: ConfigMap
metadata:
  name: hyplex-services-config
  namespace: hyplex-gsm
data:
  REDIS_ADDR: "hyplex-redis-sentinel-sentinel.hyplex-redis.svc.cluster.local:26379"
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"
  # Agones configuration
  AGONES_ENABLED: "true"
  AGONES_NAMESPACE: "hyplex-game"
  GAME_SERVER_IMAGE: "ghcr.io/hyplex-network/game-server"
  GAME_SERVER_VERSION: "latest"
