apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: prometheus-operator-crds
    version: 25.0.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-operator-crds