apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podmonitor.yaml
helmCharts:
  - name: nack
    version: "0.31.1"
    repo: https://nats-io.github.io/k8s/helm/charts/
    releaseName: nack
    namespace: nats-nack
    valuesFile: values.yaml
