apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: gloo-gateway-crds
    includeCRDs: true
    version: 2.0.1
    repo: oci://us-docker.pkg.dev/solo-public/gloo-gateway/charts
    releaseName: gloo-gateway-crds
    namespace: gloo-system
  - name: gloo-gateway
    version: 2.0.1
    repo: oci://us-docker.pkg.dev/solo-public/gloo-gateway/charts
    releaseName: gloo-gateway
    namespace: gloo-system
    valuesFile: values.yaml