glooGateway:
  enabled: true

gateway:
  enabled: true

global:
  networkPolicy:
    enabled: true
  image:
    pullPolicy: IfNotPresent

kgateway:
  enabled: true
  istioIntegration:
    enabled: false # Enable later when we move to Istio Ambient