apiVersion: v1
kind: ConfigMap
metadata:
  name: hyplex-services-config
  namespace: hyplex-configuration
data:
  REDIS_ADDR: "hyplex-redis-sentinel.hyplex-redis.svc.cluster.local:26379"
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"
