apiVersion: v1
kind: ConfigMap
metadata:
  name: netbird-dashboard-env
  namespace: netbird
data:
  NETBIRD_MGMT_API_ENDPOINT: "https://netbird.vngenterprise.com"
  NETBIRD_MGMT_GRPC_API_ENDPOINT: "https://netbird.vngenterprise.com"
  AUTH_AUDIENCE: "360524786834670002"
  AUTH_CLIENT_ID: "360524786834670002"
  AUTH_AUTHORITY: "https://accounts.vngenterprise.com"
  USE_AUTH0: "false"
  AUTH_SUPPORTED_SCOPES: "openid profile email offline_access"
  AUTH_REDIRECT_URI: "/nb-auth"
  AUTH_SILENT_REDIRECT_URI: "/nb-silent-auth"
  NGINX_SSL_PORT: "443"
  LETSENCRYPT_DOMAIN: "none"
  LETSENCRYPT_EMAIL: "frankd@vngenterprise.com"
