---
apiVersion: v1
kind: Service
metadata:
  name: netbird-dashboard
  namespace: netbird
spec:
  selector:
    app: netbird-dashboard
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-signal
  namespace: netbird
spec:
  selector:
    app: netbird-signal
  ports:
    - name: grpc
      port: 10000
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-relay
  namespace: netbird
spec:
  selector:
    app: netbird-relay
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-management
  namespace: netbird
spec:
  selector:
    app: netbird-management
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-coturn-lb
  namespace: netbird
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.50.180
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: netbird-coturn
  ports:
    - name: stun-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: stun-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
    - name: turn-tls
      port: 5349
      protocol: TCP
      targetPort: 5349
    - name: relay-50000
      port: 50000
      protocol: UDP
      targetPort: 50000
    - name: relay-50001
      port: 50001
      protocol: UDP
      targetPort: 50001
    - name: relay-50002
      port: 50002
      protocol: UDP
      targetPort: 50002
    - name: relay-50003
      port: 50003
      protocol: UDP
      targetPort: 50003
    - name: relay-50004
      port: 50004
      protocol: UDP
      targetPort: 50004
    - name: relay-50005
      port: 50005
      protocol: UDP
      targetPort: 50005
    - name: relay-50006
      port: 50006
      protocol: UDP
      targetPort: 50006
    - name: relay-50007
      port: 50007
      protocol: UDP
      targetPort: 50007
    - name: relay-50008
      port: 50008
      protocol: UDP
      targetPort: 50008
    - name: relay-50009
      port: 50009
      protocol: UDP
      targetPort: 50009
    - name: relay-50010
      port: 50010
      protocol: UDP
      targetPort: 50010
    - name: relay-50011
      port: 50011
      protocol: UDP
      targetPort: 50011
    - name: relay-50012
      port: 50012
      protocol: UDP
      targetPort: 50012
    - name: relay-50013
      port: 50013
      protocol: UDP
      targetPort: 50013
    - name: relay-50014
      port: 50014
      protocol: UDP
      targetPort: 50014
    - name: relay-50015
      port: 50015
      protocol: UDP
      targetPort: 50015
    - name: relay-50016
      port: 50016
      protocol: UDP
      targetPort: 50016
    - name: relay-50017
      port: 50017
      protocol: UDP
      targetPort: 50017
    - name: relay-50018
      port: 50018
      protocol: UDP
      targetPort: 50018
    - name: relay-50019
      port: 50019
      protocol: UDP
      targetPort: 50019
    - name: relay-50020
      port: 50020
      protocol: UDP
      targetPort: 50020
    - name: relay-50021
      port: 50021
      protocol: UDP
      targetPort: 50021
    - name: relay-50022
      port: 50022
      protocol: UDP
      targetPort: 50022
    - name: relay-50023
      port: 50023
      protocol: UDP
      targetPort: 50023
    - name: relay-50024
      port: 50024
      protocol: UDP
      targetPort: 50024
    - name: relay-50025
      port: 50025
      protocol: UDP
      targetPort: 50025
    - name: relay-50026
      port: 50026
      protocol: UDP
      targetPort: 50026
    - name: relay-50027
      port: 50027
      protocol: UDP
      targetPort: 50027
    - name: relay-50028
      port: 50028
      protocol: UDP
      targetPort: 50028
    - name: relay-50029
      port: 50029
      protocol: UDP
      targetPort: 50029
    - name: relay-50030
      port: 50030
      protocol: UDP
      targetPort: 50030
    - name: relay-50031
      port: 50031
      protocol: UDP
      targetPort: 50031
    - name: relay-50032
      port: 50032
      protocol: UDP
      targetPort: 50032
    - name: relay-50033
      port: 50033
      protocol: UDP
      targetPort: 50033
    - name: relay-50034
      port: 50034
      protocol: UDP
      targetPort: 50034
    - name: relay-50035
      port: 50035
      protocol: UDP
      targetPort: 50035
    - name: relay-50036
      port: 50036
      protocol: UDP
      targetPort: 50036
    - name: relay-50037
      port: 50037
      protocol: UDP
      targetPort: 50037
    - name: relay-50038
      port: 50038
      protocol: UDP
      targetPort: 50038
    - name: relay-50039
      port: 50039
      protocol: UDP
      targetPort: 50039
    - name: relay-50040
      port: 50040
      protocol: UDP
      targetPort: 50040
    - name: relay-50041
      port: 50041
      protocol: UDP
      targetPort: 50041
    - name: relay-50042
      port: 50042
      protocol: UDP
      targetPort: 50042
    - name: relay-50043
      port: 50043
      protocol: UDP
      targetPort: 50043
    - name: relay-50044
      port: 50044
      protocol: UDP
      targetPort: 50044
    - name: relay-50045
      port: 50045
      protocol: UDP
      targetPort: 50045
    - name: relay-50046
      port: 50046
      protocol: UDP
      targetPort: 50046
    - name: relay-50047
      port: 50047
      protocol: UDP
      targetPort: 50047
    - name: relay-50048
      port: 50048
      protocol: UDP
      targetPort: 50048
    - name: relay-50049
      port: 50049
      protocol: UDP
      targetPort: 50049
    - name: relay-50050
      port: 50050
      protocol: UDP
      targetPort: 50050
    - name: relay-50051
      port: 50051
      protocol: UDP
      targetPort: 50051
    - name: relay-50052
      port: 50052
      protocol: UDP
      targetPort: 50052
    - name: relay-50053
      port: 50053
      protocol: UDP
      targetPort: 50053
    - name: relay-50054
      port: 50054
      protocol: UDP
      targetPort: 50054
    - name: relay-50055
      port: 50055
      protocol: UDP
      targetPort: 50055
    - name: relay-50056
      port: 50056
      protocol: UDP
      targetPort: 50056
    - name: relay-50057
      port: 50057
      protocol: UDP
      targetPort: 50057
    - name: relay-50058
      port: 50058
      protocol: UDP
      targetPort: 50058
    - name: relay-50059
      port: 50059
      protocol: UDP
      targetPort: 50059
    - name: relay-50060
      port: 50060
      protocol: UDP
      targetPort: 50060
    - name: relay-50061
      port: 50061
      protocol: UDP
      targetPort: 50061
    - name: relay-50062
      port: 50062
      protocol: UDP
      targetPort: 50062
    - name: relay-50063
      port: 50063
      protocol: UDP
      targetPort: 50063
    - name: relay-50064
      port: 50064
      protocol: UDP
      targetPort: 50064
    - name: relay-50065
      port: 50065
      protocol: UDP
      targetPort: 50065
    - name: relay-50066
      port: 50066
      protocol: UDP
      targetPort: 50066
    - name: relay-50067
      port: 50067
      protocol: UDP
      targetPort: 50067
    - name: relay-50068
      port: 50068
      protocol: UDP
      targetPort: 50068
    - name: relay-50069
      port: 50069
      protocol: UDP
      targetPort: 50069
    - name: relay-50070
      port: 50070
      protocol: UDP
      targetPort: 50070
    - name: relay-50071
      port: 50071
      protocol: UDP
      targetPort: 50071
    - name: relay-50072
      port: 50072
      protocol: UDP
      targetPort: 50072
    - name: relay-50073
      port: 50073
      protocol: UDP
      targetPort: 50073
    - name: relay-50074
      port: 50074
      protocol: UDP
      targetPort: 50074
    - name: relay-50075
      port: 50075
      protocol: UDP
      targetPort: 50075
    - name: relay-50076
      port: 50076
      protocol: UDP
      targetPort: 50076
    - name: relay-50077
      port: 50077
      protocol: UDP
      targetPort: 50077
    - name: relay-50078
      port: 50078
      protocol: UDP
      targetPort: 50078
    - name: relay-50079
      port: 50079
      protocol: UDP
      targetPort: 50079
    - name: relay-50080
      port: 50080
      protocol: UDP
      targetPort: 50080
    - name: relay-50081
      port: 50081
      protocol: UDP
      targetPort: 50081
    - name: relay-50082
      port: 50082
      protocol: UDP
      targetPort: 50082
    - name: relay-50083
      port: 50083
      protocol: UDP
      targetPort: 50083
    - name: relay-50084
      port: 50084
      protocol: UDP
      targetPort: 50084
    - name: relay-50085
      port: 50085
      protocol: UDP
      targetPort: 50085
    - name: relay-50086
      port: 50086
      protocol: UDP
      targetPort: 50086
    - name: relay-50087
      port: 50087
      protocol: UDP
      targetPort: 50087
    - name: relay-50088
      port: 50088
      protocol: UDP
      targetPort: 50088
    - name: relay-50089
      port: 50089
      protocol: UDP
      targetPort: 50089
    - name: relay-50090
      port: 50090
      protocol: UDP
      targetPort: 50090
    - name: relay-50091
      port: 50091
      protocol: UDP
      targetPort: 50091
    - name: relay-50092
      port: 50092
      protocol: UDP
      targetPort: 50092
    - name: relay-50093
      port: 50093
      protocol: UDP
      targetPort: 50093
    - name: relay-50094
      port: 50094
      protocol: UDP
      targetPort: 50094
    - name: relay-50095
      port: 50095
      protocol: UDP
      targetPort: 50095
    - name: relay-50096
      port: 50096
      protocol: UDP
      targetPort: 50096
    - name: relay-50097
      port: 50097
      protocol: UDP
      targetPort: 50097
    - name: relay-50098
      port: 50098
      protocol: UDP
      targetPort: 50098
    - name: relay-50099
      port: 50099
      protocol: UDP
      targetPort: 50099
    - name: relay-50100
      port: 50100
      protocol: UDP
      targetPort: 50100
