apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: rollout-operator
    version: "0.37.1"
    repo: https://grafana.github.io/helm-charts
    releaseName: rollout-operator
    namespace: default