apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: life
  namespace: life
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik-external
  tls:
    - hosts:
        - life.vngenterprise.com
      secretName: life-tls
  rules:
    - host: life.vngenterprise.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: life
                port:
                  number: 80
