apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: life
  namespace: life
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`life.vngenterprise.com`)
      kind: Rule
      services:
        - name: life
          port: 80
  tls:
    store:
      name: default
      namespace: traefik
